
all:
  children:
    k8s_vms:
      hosts:
        192.168.21.105:
        192.168.21.106:
        192.168.21.107:
    k8s_storages:
      hosts:
        192.168.21.108:
  vars:
    ansible_user: ubuntu
