- name: "Inastall Docker for K8s"
  hosts: all
  become: yes

  tasks:

  - name: Install Docker
    apt:
      update_cache: yes
      pkg:
      -  docker
      -  docker-compose

  - name: Add user to gorup
    user:
      name: ubuntu
      group: docker
      append: yes
